document.write(typeof "Word");
document.write("10" + 3);
document.getElementById("Test").innerHTML = isNaN('This is a string');
document.getElementById("Test").innerHTML = isNaN('7');
document.getElementById("Test").innerHTML = isNaN('007');
document.write(2E310);
document.write(-3E310);
document.write(10 > 2);
document.write(10 < 2);
console.log(2 + 2);
